### ISSUE TITLE
Integration test failure

### ISSUE THREAD

**Issue by alexanderem49** [alexanderem49/simple-exchange#18]
The integration test is failing with error `Promise returned by test never resolved`

```
yarn run v1.22.5
$ cd contract && yarn test test/integrationTests
$ ava --verbose test/integrationTests

Removing intrinsics.Symbol.dispose
Removing intrinsics.Symbol.asyncDispose
[bundleTool] bundles/ bundle-walletFactory.js valid: 148 files bundled at 2023-10-26T09:03:15.545Z 
----- WltFct.4  2 makeAssetRegistry Object [Alleged: Bank] {}
  ✖ test make sell offer Promise returned by test never resolved
  ─

  test make sell offer

  Error: Promise returned by test never resolved
    at process.emit (node:events:517:28)

  ─

  1 test failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Debugging shows that error happens at [this](https://github.com/alexanderem49/simple-exchange/blob/42f935cfe92424b21e824ff5b48fd9799831807a/contract/test/integrationTests/test-integration.js#L92) line, inside `setupFakeAgoricNamesWithAssets` function.

Constant `agoricNamesAdmin` at this line is a promise in pending state. Awaiting this promise immediately throws an error, seems like this is the promise that never resolves

Inside `setupFakeAgoricNamesWithAssets` it fails when awaiting `Promise.all` with 2 promises inside.

**Comment by alexanderem49** [comment]
Checking out agoric-sdk on `agoric-upgrade-11wf` fixes this issue, all tests are passing. Looks like there is a bug in SDK on commit `92b6cd72484079b0349d8ccfa4510aeb820e8d67` which was fixed later.

**Comment by Jorge-Lopes** [comment]
## Context
There are two issues that I identified that are being triggered when running the test-integration while using the agoric-sdk staged at `92b6cd72484079b0349d8ccfa4510aeb820e8d67`.

### Issue 1
The `agoricNamesAdmin` will return an unresolved promise, which prevent us from injecting the two assets created on the agoricNames.
The reason is related to the `makeMockTestSpace` method, imported from `@agoric/smart-wallet/test/supports.js`
If you analyse this method, you will notice that the agoricNamesAdmin was not provided by the makeAgoricNamesAccess methyod
```
  const { agoricNames, spaces } = await makeAgoricNamesAccess();
  produce.agoricNames.resolve(agoricNames);
```

Although, we can see that this was address on the [PR#8311](https://github.com/Agoric/agoric-sdk/commit/e669bb12f560d84f7fc017abda49d3dd6d5cee17#diff-0c75f76f650658548cbe43c4426beecb665522f56da74c427b845d5c651911dc) 

### Issue 2
Even when I made the required changes to the packages/smart-wallet/test/supports.js file, that payments that provide to the smartWallet required to make an sell/buy order were not being executed. The wallet purse would not show the payment.
```
  const sellerMoolaPayment = moolaKit.mint.mintPayment(moolaAmount);
  await E(depositFacetSeller).receive(sellerMoolaPayment);
```
Although, when we add an invitation to the purse, it will behave as expected.
Note that I verified, and the assets created were correctly injected in the agoricNames

I don't know the source of this issue, but I will keep pushing to find new ways to debug this issue.

## Solution
In the meanwhile, we should add a note visible in the project README file and tutorial that to execute the swignset tests, the developer should checkout the agoric-sdk to the following commit: [e669bb1](https://github.com/Agoric/agoric-sdk/commit/e669bb12f560d84f7fc017abda49d3dd6d5cee17)
